apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 134319464995.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 134319464995.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: 416d0bd2
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
